### ISSUE TITLE
PHP Fatal error:  'break' not in the 'loop' or 'switch'

### ISSUE THREAD

**Issue by wildandotid** [komeine/lineTimeline#1]
[Wed Feb 01 15:57:16.567197 2017] [:error] [pid 4310] [client ::1:41512] PHP Fatal error:  'break' not in the 'loop' or 'switch' context in /var/www/html/line/src/LineTimeline.php on line 90, referer: http://localhost/line/example/

why?

**Comment by komeine** [comment]
coba gunakan php 5.6 <
