### ISSUE TITLE
New

### ISSUE THREAD

**Issue by ikiganteng** [komeine/lineTimeline#2]
`	 /*
        @title Get Sticker
        @param
        @return
    */
    public function sticker(){
		$this->sessID();
        $http = $this->response($this->http('sticker/list.json'));
        if($this->isOK()){
            return $http['products'];
        } else {
            throw new Exception('Invalid sesssion!');
        }
    }`

**Comment by ikiganteng** [comment]
> 	 /*
        @title Get Sticker
        @param
        @return
    */
    public function sticker(){
		$this->sessID();
        $http = $this->response($this->http('sticker/list.json'));
        if($this->isOK()){
            return $http['products'];
        } else {
            throw new Exception('Invalid sesssion!');
        }
    }

**Comment by komeine** [comment]
masalahnya apa ya ?

**Comment by ikiganteng** [comment]
tidak ada kak, cuman nambah aja
